### PR TITLE
preparation for upcoming cohort

### PR DESCRIPTION
**Pull request by insop**
- Minor follow ups from https://github.com/cgpotts/cs224u/pull/133

### CODE REVIEW

**Comment by insop** [comment]
Hi @cgpotts 

PTAL, it'd be good to merge now, any might be better to be merged before @SebastianHurubaru 's PR.
I will update the local llm note after this PR and @SebastianHurubaru 's PR.

Thank you,

**Comment by cgpotts** [comment]
I'll merge now. I am now nervous what will happen with @SebastianHurubaru's PR, since notebooks never get handled well, but we'll see!

**Comment by insop** [comment]
> I'll merge now. I am now nervous what will happen with @SebastianHurubaru's PR, since notebooks never get handled well, but we'll see!

Thank you @cgpotts .

I'd think @SebastianHurubaru would need to do manual merge (using `meld` or other tools) for notebook and update his PR.

I will coordinate with @SebastianHurubaru for any issues in his PR.

**Comment by SebastianHurubaru** [comment]
Hi @cgpotts , @insop my fork branch was already based on @insop's work, so there should be no conflicts.

**Pull request merged**
