### PR TITLE
Typo fix in `test_subword_enrichment`:

### PR DESCRIPTION
**Pull request by insop**
- s/X_test/expected/

### CODE REVIEW

**Comment by insop** [comment]
Hi @cgpotts 

I was checking my code against `test_subword_enrichment()`, and my result doesn't match with `expected`.
I just wanted to check with you that is the test case is valid since it seems that this is _newly_ added for the upcoming quarter and I wanted to check.
Thank you very much,

**Comment by cgpotts** [comment]
@insop Thanks again for your input on this. Would you mind writing to me at cgpotts@stanford.edu? If you include your `subword_enrichment` code, I can check it over and compare it to mine. If you prefer not to do that, then I can share my solution with you and perhaps you'll see the issue.

**Comment by cgpotts** [comment]
@insop Hey, actually, maybe never mind? I pushed an update to `hw_wordsim.ipynb` that might correct the problem. The main change is that I think I had the `expected` values wrong!

**Comment by insopsong** [comment]
Hi @cgpotts 

Thank for checking this. I went back and checked my notebook and my result matched with the updated value.

Here was my note:

Screen Shot 2020-01-12 at 13 02 53

**Comment by cgpotts** [comment]
@insop Very reassuring! I had simply messed it up!

**Pull request merged**
